### ISSUE TITLE
[13.0] [BUG]"remove_odoo_enterprise" module > Error when debug mode / view fields on any view

### ISSUE THREAD

**Issue by NCS-75** [OCA/server-brand#19]
When trying to "view fields" in debug mode from developer tolls,  regarding any tree, or form view ... (debug mode / view fields). There is an error message:

`Odoo Server Error
Traceback (most recent call last):
..../
TypeError: search() missing 1 required positional argument: 'domain'
`
1. I create a fresh new database with odoo demo data
2. I activate the developer mode, in setting
3. I goo to any list view or open any form view (eg Sale/Qotation)
4. I click to "View Fields" in developer tool menu
5. I can see the requested view of fiels (= It's OK)
6. Then, i install "remove_odoo_enterprise" module ( Install completed. OK)
7. I goo to any list view or open any form view (eg Sale/Qotation again, or any other)
8. I click to "View Fields" in developer tool menu
-9. Then, i get the issue
No issue faced after module uninstalled...

os: ubuntu 18.04
Odoo OCB 13.0 2019.12.28
odoo db new clean with demo data
"remove_odoo_enterprise" downloaded = last

![Odoo-error with remove_odoo_enterprise module_1 ](https://user-images.githubusercontent.com/59052920/72005811-ba244b00-324e-11ea-864e-819de11f48d2.png)
![Odoo-error with remove_odoo_enterprise module_2 ](https://user-images.githubusercontent.com/59052920/72005812-ba244b00-324e-11ea-995d-97402ecb9fca.png)

**Comment by NCS-75** [comment]
> This upside error can be checked now,  on OCA  [runbot ](http://3404026-13-0-f0490c.runbot1.odoo-community.org/)

**Comment by astirpe** [comment]
@NCS-75 should be fixed in https://github.com/OCA/server-brand/pull/20, could you check?

**Comment by NCS-75** [comment]
@astirpe Issue still remaining after your fix proposal ; sorry...
1. I 've updated the whole "remove_odoo_enterprise" module repository on my server,  from [https://github.com/onesteinbv/server-brand/tree/13_fix_remove_odoo_enterprise/remove_odoo_enterprise ], and resarted odoo deamon
2. I 've upgaded the module from Apps menu in my test database
3. Then, i still face the issue
4. i create a new database test
5. Then, again , i still face the issue

**Comment by astirpe** [comment]
I guess your old version of the module is somewhere there and still running.
You can test #20 in Runbot and verify that it fixes the bug.
Runbot: http://3404128-20-b9e29b.runbot3.odoo-community.org/web/login

**Comment by NCS-75** [comment]
@astirpe 👍 Issue is fixed, now
Sorry for inconveniance of test fix
1. I've deleted all  "__pycache__" repository into module 

> (Was the reason of remaining issue ?)

2. I 've restart Odoo deamon, and have upgaded the module from Apps menu
3. Then, no more issue...
Thanks for reactivity

**Comment by astirpe** [comment]
Thanks @NCS-75 
Could you please go to https://github.com/OCA/server-brand/pull/20/files, Review Changes, and then Approve?

**Comment by sergioeix** [comment]
I am gettin this error too tried https://github.com/OCA/server-brand/issues/19#issuecomment-572550478 
1 I've deleted all "pycache" repository into module
2 reboot odoo server and have upgaded the module from Apps menu
3 the issue remains
Tried to uninstall the menu and all works as spected
os: ubuntu 18.04
Odoo OCB 13.0
![image](https://user-images.githubusercontent.com/62206774/77753846-92ad7500-702a-11ea-92c5-fa323f859b10.png)
Thanks
